In [2]:
import pandas as pd
import numpy as np

# Series


### Series from list

In [3]:

name = ["Khushbu","Ketan","Harshal","Vaibhav"]
pd.Series(name)

0    Khushbu
1      Ketan
2    Harshal
3    Vaibhav
dtype: object

In [5]:
marks = [90,93,85,72]
pd.Series(marks)

0    90
1    93
2    85
3    72
dtype: int64

In [6]:
subjects = ["Hindi","English","Science","Maths"]

In [8]:
pd.Series(marks, index = subjects)

Hindi      90
English    93
Science    85
Maths      72
dtype: int64

In [10]:
pd.Series(marks, index = subjects, name = "Khushbu's marks", dtype = "float")

Hindi      90.0
English    93.0
Science    85.0
Maths      72.0
Name: Khushbu's marks, dtype: float64

### Series from tuple

In [12]:
abc = (1,2,3,6)
pd.Series(abc)

0    1
1    2
2    3
3    6
dtype: int64

In [14]:
abc = (1,2,3,6)
pd.Series(abc, index = ('a','b','c','d'))

a    1
b    2
c    3
d    6
dtype: int64

### Series from Dictionary

In [15]:
marks= {
    "Maths":98,
    "Physics":95,
    "Chemistry":67,
    "English":94,
    "Physical Education":98,
    "Computer Science":93
}

In [16]:
a = pd.Series(marks)
a

Maths                 98
Physics               95
Chemistry             67
English               94
Physical Education    98
Computer Science      93
dtype: int64

In [19]:
a["Physics"]

95

### Slicing and Indexing

In [23]:
series = pd.Series((1,5,3,2,1,5,6,3,2,1,8,9,6,3,5), name = 'abc')

In [24]:
series

0     1
1     5
2     3
3     2
4     1
5     5
6     6
7     3
8     2
9     1
10    8
11    9
12    6
13    3
14    5
Name: abc, dtype: int64

In [26]:
series[1:12:2]

1     5
3     2
5     5
7     3
9     1
11    9
Name: abc, dtype: int64

#### Series Attributes

In [27]:
a

Maths                 98
Physics               95
Chemistry             67
English               94
Physical Education    98
Computer Science      93
dtype: int64

In [33]:
series.size

15

In [34]:
series.dtype

dtype('int64')

In [35]:
series.name

'abc'

In [36]:
series.is_unique

False

In [37]:
series.values

array([1, 5, 3, 2, 1, 5, 6, 3, 2, 1, 8, 9, 6, 3, 5], dtype=int64)

In [38]:
series.index

RangeIndex(start=0, stop=15, step=1)

In [39]:
a.index

Index(['Maths', 'Physics', 'Chemistry', 'English', 'Physical Education',
       'Computer Science'],
      dtype='object')

In [40]:
a

Maths                 98
Physics               95
Chemistry             67
English               94
Physical Education    98
Computer Science      93
dtype: int64

In [41]:
series.unique()

array([1, 5, 3, 2, 6, 8, 9], dtype=int64)

In [42]:
series.value_counts()

abc
1    3
5    3
3    3
2    2
6    2
8    1
9    1
Name: count, dtype: int64

In [43]:
# updating value

In [44]:
a

Maths                 98
Physics               95
Chemistry             67
English               94
Physical Education    98
Computer Science      93
dtype: int64

In [45]:
a["English"] = 97

In [46]:
a

Maths                 98
Physics               95
Chemistry             67
English               97
Physical Education    98
Computer Science      93
dtype: int64

In [47]:
# Adding value
a["Music"] = 87

In [48]:
a

Maths                 98
Physics               95
Chemistry             67
English               97
Physical Education    98
Computer Science      93
Music                 87
dtype: int64

In [49]:
# Dropping value
a.drop("Music")

Maths                 98
Physics               95
Chemistry             67
English               97
Physical Education    98
Computer Science      93
dtype: int64

In [50]:
a

Maths                 98
Physics               95
Chemistry             67
English               97
Physical Education    98
Computer Science      93
Music                 87
dtype: int64

In [51]:
a.drop("Music",inplace = True)

In [52]:
a

Maths                 98
Physics               95
Chemistry             67
English               97
Physical Education    98
Computer Science      93
dtype: int64

In [53]:
# Arithmatic Operation
a+100

Maths                 198
Physics               195
Chemistry             167
English               197
Physical Education    198
Computer Science      193
dtype: int64

In [57]:
#Comparision Operation
a>95

Maths                  True
Physics               False
Chemistry             False
English                True
Physical Education     True
Computer Science      False
dtype: bool

In [58]:
a[a>95]

Maths                 98
English               97
Physical Education    98
dtype: int64

In [59]:
series = pd.Series(range(0,10000,5), index= (i for i in range(100, 200100, 100)))

In [60]:
series

100          0
200          5
300         10
400         15
500         20
          ... 
199600    9975
199700    9980
199800    9985
199900    9990
200000    9995
Length: 2000, dtype: int64

In [61]:
series.head()

100     0
200     5
300    10
400    15
500    20
dtype: int64

In [62]:
series.tail(3)

199800    9985
199900    9990
200000    9995
dtype: int64

In [63]:
series.sample(7)

180800    9035
6900       340
23900     1190
122800    6135
111700    5580
147900    7390
19800      985
dtype: int64

In [64]:
import random

In [65]:
names = [
'Amit', 'Ravi', 'Suresh', 'Priya', 'Anita', 'Vikas', 'Neha', 'Shreya', 'Rahul', 'Siddharth',
'Sonia', 'Varun', 'Rajesh', 'Aarti', 'Deepak', 'Kiran', 'Pooja', 'Rohit', 'Isha', 'Anjali',
'Sandeep', 'Tanvi', 'Maya', 'Nisha', 'Aman', 'Yash', 'Kavita', 'Aakash', 'Sonali', 'Manish',
'Bhavesh', 'Siddhi', 'Neelam', 'Nikhil', 'Ashwini', 'Vishal', 'Sakshi', 'Kunal', 'Ritika',
'Parth', 'Tanuja', 'Shubham', 'Nikita', 'Harish', 'Pratik', 'Kriti', 'Geeta', 'Avi', 'Arun',"Ajay","Akshay", "Shyam","Pranav"
]

In [88]:
student_marks = pd.Series([random.randint(80,100) for i in range(53)], index = names)

In [89]:
len(names)

53

In [90]:
student_marks

Amit          94
Ravi          95
Suresh        91
Priya         80
Anita         96
Vikas         99
Neha          95
Shreya        83
Rahul        100
Siddharth     89
Sonia         94
Varun         94
Rajesh       100
Aarti         85
Deepak        83
Kiran         80
Pooja         86
Rohit         87
Isha          80
Anjali        86
Sandeep       92
Tanvi         96
Maya          88
Nisha         86
Aman          85
Yash          81
Kavita        86
Aakash        84
Sonali        94
Manish        81
Bhavesh       84
Siddhi        94
Neelam       100
Nikhil        97
Ashwini       84
Vishal        90
Sakshi        96
Kunal         85
Ritika        90
Parth         83
Tanuja        89
Shubham       80
Nikita        92
Harish        86
Pratik        98
Kriti         96
Geeta         92
Avi           95
Arun          96
Ajay          96
Akshay        95
Shyam         90
Pranav        88
dtype: int64

In [91]:
student_marks.count()

53

In [92]:
len(student_marks)

53

In [93]:
student_marks.mean()

89.9245283018868

In [94]:
student_marks.sum()

4766

In [95]:
student_marks.median()

90.0

In [96]:
student_marks.max()

100

In [97]:
student_marks.min()

80

In [98]:
student_marks.mode()[0]

96

In [99]:
student_marks.std()

6.034672435835889

In [100]:
student_marks.var()

36.417271407837454

In [101]:
# 8 Point summary
student_marks.describe()

count     53.000000
mean      89.924528
std        6.034672
min       80.000000
25%       85.000000
50%       90.000000
75%       95.000000
max      100.000000
dtype: float64

In [102]:
student_marks.unique()

array([ 94,  95,  91,  80,  96,  99,  83, 100,  89,  85,  86,  87,  92,
        88,  81,  84,  97,  90,  98], dtype=int64)

In [103]:
student_marks.nunique()

19

In [104]:
student_marks.value_counts()

96     6
94     5
86     5
95     4
80     4
90     3
84     3
92     3
85     3
100    3
83     3
89     2
88     2
81     2
87     1
99     1
97     1
91     1
98     1
Name: count, dtype: int64

In [105]:
student_marks.index

Index(['Amit', 'Ravi', 'Suresh', 'Priya', 'Anita', 'Vikas', 'Neha', 'Shreya',
       'Rahul', 'Siddharth', 'Sonia', 'Varun', 'Rajesh', 'Aarti', 'Deepak',
       'Kiran', 'Pooja', 'Rohit', 'Isha', 'Anjali', 'Sandeep', 'Tanvi', 'Maya',
       'Nisha', 'Aman', 'Yash', 'Kavita', 'Aakash', 'Sonali', 'Manish',
       'Bhavesh', 'Siddhi', 'Neelam', 'Nikhil', 'Ashwini', 'Vishal', 'Sakshi',
       'Kunal', 'Ritika', 'Parth', 'Tanuja', 'Shubham', 'Nikita', 'Harish',
       'Pratik', 'Kriti', 'Geeta', 'Avi', 'Arun', 'Ajay', 'Akshay', 'Shyam',
       'Pranav'],
      dtype='object')

In [106]:
student_marks.values

array([ 94,  95,  91,  80,  96,  99,  95,  83, 100,  89,  94,  94, 100,
        85,  83,  80,  86,  87,  80,  86,  92,  96,  88,  86,  85,  81,
        86,  84,  94,  81,  84,  94, 100,  97,  84,  90,  96,  85,  90,
        83,  89,  80,  92,  86,  98,  96,  92,  95,  96,  96,  95,  90,
        88], dtype=int64)

In [107]:
student_marks.sort_values()

Shubham       80
Priya         80
Isha          80
Kiran         80
Manish        81
Yash          81
Parth         83
Shreya        83
Deepak        83
Aakash        84
Ashwini       84
Bhavesh       84
Kunal         85
Aman          85
Aarti         85
Anjali        86
Kavita        86
Nisha         86
Harish        86
Pooja         86
Rohit         87
Maya          88
Pranav        88
Tanuja        89
Siddharth     89
Shyam         90
Ritika        90
Vishal        90
Suresh        91
Sandeep       92
Geeta         92
Nikita        92
Amit          94
Varun         94
Siddhi        94
Sonali        94
Sonia         94
Neha          95
Akshay        95
Ravi          95
Avi           95
Sakshi        96
Tanvi         96
Anita         96
Ajay          96
Arun          96
Kriti         96
Nikhil        97
Pratik        98
Vikas         99
Neelam       100
Rahul        100
Rajesh       100
dtype: int64

In [110]:
student_marks.sort_values(ascending=False, inplace = True)

In [111]:
student_marks

Neelam       100
Rahul        100
Rajesh       100
Vikas         99
Pratik        98
Nikhil        97
Ajay          96
Anita         96
Sakshi        96
Tanvi         96
Kriti         96
Arun          96
Ravi          95
Avi           95
Akshay        95
Neha          95
Varun         94
Siddhi        94
Sonia         94
Sonali        94
Amit          94
Geeta         92
Nikita        92
Sandeep       92
Suresh        91
Ritika        90
Vishal        90
Shyam         90
Siddharth     89
Tanuja        89
Pranav        88
Maya          88
Rohit         87
Anjali        86
Nisha         86
Pooja         86
Harish        86
Kavita        86
Kunal         85
Aman          85
Aarti         85
Ashwini       84
Aakash        84
Bhavesh       84
Parth         83
Deepak        83
Shreya        83
Manish        81
Yash          81
Shubham       80
Isha          80
Kiran         80
Priya         80
dtype: int64

#### Filtering of data

In [114]:
# Name of students who scored more than 90 marks
student_marks[student_marks>90].index

Index(['Neelam', 'Rahul', 'Rajesh', 'Vikas', 'Pratik', 'Nikhil', 'Ajay',
       'Anita', 'Sakshi', 'Tanvi', 'Kriti', 'Arun', 'Ravi', 'Avi', 'Akshay',
       'Neha', 'Varun', 'Siddhi', 'Sonia', 'Sonali', 'Amit', 'Geeta', 'Nikita',
       'Sandeep', 'Suresh'],
      dtype='object')

In [120]:
# Count of students who scored less than 87 marks
student_marks[student_marks<87].size

20

In [124]:
# Name of students who scored between 85 and 95
student_marks[(student_marks >=85) & (student_marks<=95)]

Ravi         95
Avi          95
Akshay       95
Neha         95
Varun        94
Siddhi       94
Sonia        94
Sonali       94
Amit         94
Geeta        92
Nikita       92
Sandeep      92
Suresh       91
Ritika       90
Vishal       90
Shyam        90
Siddharth    89
Tanuja       89
Pranav       88
Maya         88
Rohit        87
Anjali       86
Nisha        86
Pooja        86
Harish       86
Kavita       86
Kunal        85
Aman         85
Aarti        85
dtype: int64